import 'dart:convert';

import 'package:flutter/services.dart' show AssetBundle, rootBundle;

/// Loads the bundled Mode B word-frequency list.
abstract interface class WordFreqLocalDataSource {
  /// Parses `assets/word_freq.json` and returns word → corpus count.
  /// Throws on a missing or malformed asset; the repository decides what
  /// unavailability means for the app.
  Future<Map<String, int>> load();
}

/// Reads the asset generated by `tool/build_word_freq.py` — a `meta` block
/// (source, licence, attribution) and a flat `words` map.
class WordFreqLocalDataSourceImpl implements WordFreqLocalDataSource {
  static const assetPath = 'assets/word_freq.json';

  final AssetBundle bundle;

  WordFreqLocalDataSourceImpl({AssetBundle? bundle})
      : bundle = bundle ?? rootBundle;

  @override
  Future<Map<String, int>> load() async {
    final raw = await bundle.loadString(assetPath);
    final decoded = jsonDecode(raw) as Map<String, dynamic>;
    final words = decoded['words'] as Map<String, dynamic>;
    return words.map((word, count) => MapEntry(word, count as int));
  }
}
